language: node_js

node_js: 
  - "10"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  - npm install -g create-react-app
  - cd functions; npm install; cd ..;
  - npm install

script:
  - npm run travisDeploy